# Generated by Django 4.2.7 on 2024-02-22 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optimizationmodel',
            name='x',
        ),
    ]
